//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public string Id { get; set; }
        public string PacienteId { get; set; }
        public System.DateTime Data { get; set; }
        public string Descricao { get; set; }
        public string MedicoId { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
