//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        public string Id { get; set; }
        public string NomeGenerico { get; set; }
        public string NomeFabrica { get; set; }
        public string NomeFabricante { get; set; }
    }
}
