//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGCM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectionStringEF : DbContext
    {
        public ConnectionStringEF()
            : base("name=ConnectionStringEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Papeis> Papeis { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Especialidade> Especialidade { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Medicamento> medicamento { get; set; }
        public virtual DbSet<Exame> exame { get; set; }
        public virtual DbSet<ItemReceita> item_receita { get; set; }
        public virtual DbSet<Receita> receita { get; set; }
        public virtual DbSet<TipoExame> tipo_exame { get; set; }
        public virtual DbSet<Historico> historico { get; set; }
    }
}
